version: '2'
services:

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - /home/mscdiogo/lakehouse/minio_data:/data
    environment:
      - "MINIO_ROOT_USER=admin"               # TODO: Change
      - "MINIO_ROOT_PASSWORD=admin1234"
    command: server /data --console-address ":9090"
    networks:
      lakehouse:
        ipv4_address: 10.10.5.2

  grafana:
    #image: grafana/grafana-oss:latest-ubuntu
    image: grafana/grafana-oss:10.0.2-ubuntu
    user: "0:0"
    container_name: grafana
    platform: 'linux/amd64'
    ports:
      - "3000:3000"
    volumes:
      #- /home/mscdiogo/lakehouse/grafana/hrv_dashboard.json:/var/lib/grafana/dashboards/HRV Dashboard.json
      #- /home/mscdiogo/lakehouse/grafana/hrv_dashboard_v2.json:/var/lib/grafana/dashboards/HRV Dashboard 2.json
      #- /home/mscdiogo/lakehouse/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      #- /home/mscdiogo/lakehouse/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - /home/mscdiogo/lakehouse/grafana/grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,natel-plotly-panel,grafana-mqtt-datasource
    restart: always
    depends_on:
      - minio
      - delta_sharing_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      lakehouse:
        ipv4_address: 10.10.5.3

  delta_sharing_server:
    image: deltaio/delta-sharing-server:0.6.2
    container_name: delta-sharing-server
    ports:
      - "8080:8080"
    volumes:
      - /home/mscdiogo/lakehouse/delta-sharing/delta-sharing-server.yaml:/config/delta-sharing-server-config.yaml
      - /home/mscdiogo/lakehouse/delta-sharing/core-site.xml:/opt/docker/conf/core-site.xml  # TODO: Warning IP
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin          # TODO: Change
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: "--config /config/delta-sharing-server-config.yaml"
    depends_on:
      - minio
    networks:
      lakehouse:
        ipv4_address: 10.10.5.4

  flask_api:
    container_name: flask-api
    build: 
      context: backend
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - PORT=5000
    depends_on:
      - delta_sharing_server
    networks:
      lakehouse:
        ipv4_address: 10.10.5.5

  #mosquitto:
  #  image: eclipse-mosquitto
  #  ports:
  #    - 1883:1883
  #  volumes:
  #    - /home/mscdiogo/lakehouse/mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # TODO: Video processer
  video_processer:
    container_name: video-processer
    build: 
      context: scenario_code
      dockerfile: Dockerfile.video_processer
    depends_on:
      - delta_sharing_server
      - minio
    networks:
      lakehouse:
        ipv4_address: 10.10.5.6



networks:
  lakehouse:
    name: lakehouse_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
          gateway: 10.10.5.1

volumes:
  grafana-storage:
    external: true