# Use a base Python image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Flask API code to the container
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

# Expose the API port
EXPOSE 5000

# Start the Flask API
CMD ["python", "app.py"]
